### ISSUE TITLE
Crash: invalid virtual table when -Og option is used

### ISSUE THREAD

**Issue by ruffinakoza** [dreamland-mud/dreamland_code#158]
```
#0  0x00007f9057ab36e3 in UndefinedOneHit::damEffectSlice (
    this=this@entry=0x7ffc2aa42e3e)
    at ../../../dreamland_code/plug-ins/fight/onehit_undef.cpp:1355
#1  0x00007f9057ab45a9 in UndefinedOneHit::postDamageEffects (
    this=0x7ffc2aa42e3e)
    at ../../../dreamland_code/plug-ins/fight/onehit_undef.cpp:173
#2  0x00007f9057aaba9e in OneHit::hit (this=0x7ffc2aa52e40)
    at ../../../dreamland_code/plug-ins/fight/onehit.cpp:78
#3  0x00007f9057a8eaa0 in one_hit_nocatch (ch=<optimized out>, 
    victim=victim@entry=0x7f90440025f0, secondary=secondary@entry=false)
    at ../../../dreamland_code/plug-ins/fight/fight.cpp:339
#4  0x00007f9057a8efd6 in one_hit (ch=<optimized out>, 
    victim=victim@entry=0x7f90440025f0, secondary=secondary@entry=false)
    at ../../../dreamland_code/plug-ins/fight/fight.cpp:345

```

*this at frame 0:

```
$2 = {
  <WeaponOneHit> = {
    <OneHit> = {
      <Damage> = <invalid address>, 
      members of OneHit: 
      _vptr.OneHit = 0x0, 
      skill = 0, 
      thac0 = 0, 
      victim_ac = 0, 
      orig_dam = 0
    }, 
    members of WeaponOneHit: 
    wield = 0x0, 
    secondary = false, 
    weapon_sn = 0, 
    weaponSkill = 0x0, 
    attack = 0
  }, <No data fields>}
(gdb) 
```

*this at frame 1:
```
3 = {
  <WeaponOneHit> = {
    <OneHit> = {
      <Damage> = <invalid address>, 
      members of OneHit: 
      _vptr.OneHit = 0x0, 
      skill = 0, 
      thac0 = 0, 
      victim_ac = 0, 
      orig_dam = 0
    }, 
    members of WeaponOneHit: 
    wield = 0x0, 
    secondary = false, 
    weapon_sn = 0, 
    weaponSkill = 0x0, 
    attack = 0
  }, <No data fields>}
(gdb) 
```

*this at frame 3:
```
$4 = {
  <Damage> = {
    _vptr.Damage = 0x7f9057ccfa38 <vtable for UndefinedOneHit+232>, 
    ch = 0x5629daa73490, 
    victim = 0x7f90440025f0, 
    killer = 0x5629daa73490, 
    dam_type = 1, 
    dam = 71, 
    immune = false, 
    dam_flag = 1
  }, 
  members of OneHit: 
  _vptr.OneHit = 0x7f9057ccf968 <vtable for UndefinedOneHit+24>, 
  skill = 120, 
  thac0 = -69, 
  victim_ac = -54, 
  orig_dam = 133
}
```

The error seems to be gone with -O2 but still happen with -O2.

**Comment by ruffinakoza** [comment]
Closing as it's most likely was caused by plugins not being fully recompiled, rather than any misterious optimization issues.

**Comment by ruffinakoza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[29367] Baar: При сражении с Мезелаком (Башня Лича) мир падает](https://trello.com/c/o9KerHn8/816-29367-baar-%D0%BF%D1%80%D0%B8-%D1%81%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8-%D1%81-%D0%BC%D0%B5%D0%B7%D0%B5%D0%BB%D0%B0%D0%BA%D0%BE%D0%BC-%D0%B1%D0%B0%D1%88%D0%BD%D1%8F-%D0%BB%D0%B8%D1%87%D0%B0-%D0%BC%D0%B8%D1%80-%D0%BF%D0%B0%D0%B4%D0%B0%D0%B5%D1%82)
